services:
  cdcgov-scanner:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./secure/cdcgov_key.pem:/app/secure/cdcgov_key.pem:ro
    command: ["python", "main.py", "--org", "cdcgov","--workers", "3", "--limit", "10"]

  cdcent-scanner:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./secure/cdcent_key.pem:/app/secure/cdcent_key.pem:ro
    command: ["python", "main.py", "--org", "cdcent","--workers", "5", "--limit", "10"]